### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by pengyuguai** [annalam/breakfast#6]
1. there is no release of breakfast 0.8
2. the installation command "cargo install --release" does not work

**Comment by annalam** [comment]
Yeah, "cargo install" does not have a --release flag, it always builds in release mode.

**Comment by pengyuguai** [comment]
Thank you for your quick response!
I ran cargo install and got the following error. Could you also help me to check it?

error: failed to run custom build command for `rust-htslib v0.15.0`
process didn't exit successfully: `/home/tools/breakfast/target/release/build/rust-htslib-988658ccae386de5/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `breakfast v0.1.0 (file:///home/tools/breakfast)`, intermediate artifacts can be found at `/home/tools/breakfast/target`

Caused by:
  build failed

**Comment by annalam** [comment]
Looks like rust-htslib is not building on your platform. It's a library that Breakfast depends on. I remember seeing some rust-htslib build errors on one of our servers too. It's possible that more recent versions of rust-htslib may build on more platforms.

I just updated Cargo.toml so that Breakfast is now built against rust-htslib version 0.20, rather than the older version 0.15. I'm not getting any build errors on my end, on an Arch Linux x86_64 server.

Let me know if it builds better for you with the latest commit. If it doesn't, what kind of platform are you building on?

**Comment by annalam** [comment]
Also, it looks like on the rust-htslib [website](https://github.com/rust-bio/rust-htslib) it states that:
"To compile this crate you need the development headers of zlib, bzip2 and xz."

It might be that your platform does not have those headers installed and that's why the rust-htslib build is failing.

If you still have trouble installing with rust-htslib version 0.20, we will look into making statically linked binaries available. We need to start doing that soon anyways.

**Comment by pengyuguai** [comment]
Thank you for your help. Yeah I don't have rust-htslib installed on my ubuntu. I tried your new version of commit, however it seems like there is something wrong with the download link somewhere defined. I checked my network and it's working fine, so maybe I need to change the cargo.lock file somehow?

**Comment by annalam** [comment]
You don't need to have rust-htslib installed on your computer. It is a package that is downloaded and compiled automatically while building breakfast, and is maintained by people other than us. Your build error from earlier suggested that the rust-htslib package was not compiling properly.

If you want us to look more into this, you can paste the build or download error that you are getting now. You can also try removing the cargo.lock file, although it will probably not help.

We are not getting build errors on our servers so we are not sure what is causing the error on your computer.

**Comment by pengyuguai** [comment]
Yesterday I cannot download packages which succeeded today. But it seems that I failed compiling rust=htslib. I pasted my log here. Thank you for checking!

root@661772e4a621:/home/tools/breakfast# cargo install
  Installing breakfast v0.1.0 (file:///home/tools/breakfast)
 Downloading docopt v1.0.0
 Downloading bio v0.21.0
 Downloading rust-htslib v0.20.0
 Downloading regex v1.0.2
 Downloading strsim v0.7.0
 Downloading serde_derive v1.0.70
 Downloading lazy_static v1.0.2
 Downloading serde v1.0.70
 Downloading quote v0.6.4
 Downloading syn v0.14.5
 Downloading proc-macro2 v0.4.9
 Downloading unicode-xid v0.1.0
 Downloading utf8-ranges v1.0.0
 Downloading thread_local v0.3.5
 Downloading regex-syntax v0.6.2
 Downloading aho-corasick v0.6.6
 Downloading memchr v2.0.1
 Downloading unreachable v1.0.0
 Downloading void v1.0.2
 Downloading ucd-util v0.1.1
 Downloading libc v0.2.42
 Downloading quick-error v1.2.2
 Downloading custom_derive v0.1.7
 Downloading vec_map v0.8.1
 Downloading itertools v0.6.5
 Downloading ordered-float v0.5.0
 Downloading num-traits v0.1.43
 Downloading newtype_derive v0.1.6
 Downloading csv v1.0.0
 Downloading ndarray v0.9.1
 Downloading approx v0.1.1
 Downloading multimap v0.4.0
 Downloading regex v0.2.11
 Downloading num-integer v0.1.39
 Downloading bit-set v0.4.0
 Downloading fxhash v0.2.1
 Downloading lazy_static v0.2.11
 Downloading bv v0.7.4
 Downloading bytecount v0.3.1
 Downloading itertools-num v0.1.1
 Downloading either v1.5.0
 Downloading unreachable v0.1.1
 Downloading num-traits v0.2.5
 Downloading rustc_version v0.1.7
 Downloading semver v0.1.20
 Downloading csv-core v0.1.4
 Downloading matrixmultiply v0.1.14
 Downloading num-complex v0.1.43
 Downloading rawpointer v0.1.0
 Downloading regex-syntax v0.5.6
 Downloading bit-vec v0.4.4
 Downloading byteorder v1.2.3
 Downloading linear-map v1.2.0
 Downloading bitflags v0.9.1
 Downloading url v1.7.1
 Downloading ieee754 v0.2.2
 Downloading matches v0.1.7
 Downloading idna v0.1.5
 Downloading percent-encoding v1.0.1
 Downloading unicode-normalization v0.1.7
 Downloading unicode-bidi v0.3.4
 Downloading bindgen v0.36.1
 Downloading fs-utils v1.1.0
 Downloading quote v0.5.2
 Downloading proc-macro2 v0.3.5
 Downloading log v0.4.3
 Downloading which v1.0.5
 Downloading cexpr v0.2.3
 Downloading env_logger v0.5.11
 Downloading clap v2.32.0
 Downloading peeking_take_while v0.1.2
 Downloading clang-sys v0.22.0
 Downloading cfg-if v0.1.4
 Downloading nom v3.2.1
 Downloading memchr v1.0.2
 Downloading termcolor v1.0.1
 Downloading humantime v1.1.1
 Downloading atty v0.2.11
 Downloading textwrap v0.10.0
 Downloading unicode-width v0.1.5
 Downloading bitflags v1.0.3
 Downloading glob v0.2.11
 Downloading libloading v0.5.0
 Downloading cc v1.0.18
 Downloading ansi_term v0.11.0
   Compiling rawpointer v0.1.0
   Compiling unicode-xid v0.1.0
   Compiling cc v1.0.18
   Compiling bitflags v0.9.1
   Compiling termcolor v1.0.1
   Compiling num-traits v0.2.5
   Compiling bytecount v0.3.1
   Compiling ieee754 v0.2.2
   Compiling libc v0.2.42
   Compiling custom_derive v0.1.7
   Compiling lazy_static v1.0.2
   Compiling bv v0.7.4
   Compiling ucd-util v0.1.1
   Compiling lazy_static v0.2.11
   Compiling matrixmultiply v0.1.14
   Compiling strsim v0.7.0
   Compiling peeking_take_while v0.1.2
   Compiling bindgen v0.36.1
   Compiling linear-map v1.2.0
   Compiling regex v0.2.11
   Compiling ansi_term v0.11.0
   Compiling utf8-ranges v1.0.0
   Compiling bit-vec v0.4.4
   Compiling quick-error v1.2.2
   Compiling semver v0.1.20
   Compiling cfg-if v0.1.4
   Compiling percent-encoding v1.0.1
   Compiling matches v0.1.7
   Compiling unicode-normalization v0.1.7
   Compiling regex v1.0.2
   Compiling serde v1.0.70
   Compiling ndarray v0.9.1
   Compiling approx v0.1.1
   Compiling void v1.0.2
   Compiling bitflags v1.0.3
   Compiling byteorder v1.2.3
   Compiling either v1.5.0
   Compiling num-integer v0.1.39
   Compiling unicode-width v0.1.5
   Compiling glob v0.2.11
   Compiling log v0.4.3
   Compiling proc-macro2 v0.4.9
   Compiling proc-macro2 v0.3.5
   Compiling unicode-bidi v0.3.4
   Compiling fs-utils v1.1.0
   Compiling humantime v1.1.1
   Compiling unreachable v1.0.0
   Compiling unreachable v0.1.1
   Compiling itertools v0.6.5
   Compiling textwrap v0.10.0
   Compiling regex-syntax v0.5.6
   Compiling regex-syntax v0.6.2
   Compiling bit-set v0.4.0
   Compiling fxhash v0.2.1
   Compiling thread_local v0.3.5
   Compiling memchr v2.0.1
   Compiling memchr v1.0.2
   Compiling atty v0.2.11
   Compiling which v1.0.5
   Compiling rustc_version v0.1.7
   Compiling nom v3.2.1
   Compiling aho-corasick v0.6.6
   Compiling csv-core v0.1.4
   Compiling clang-sys v0.22.0
   Compiling newtype_derive v0.1.6
   Compiling num-traits v0.1.43
   Compiling num-complex v0.1.43
   Compiling itertools-num v0.1.1
   Compiling ordered-float v0.5.0
   Compiling quote v0.5.2
   Compiling quote v0.6.4
   Compiling syn v0.14.5
   Compiling libloading v0.5.0
   Compiling cexpr v0.2.3
   Compiling serde_derive v1.0.70
   Compiling env_logger v0.5.11
   Compiling idna v0.1.5
   Compiling url v1.7.1
   Compiling multimap v0.4.0
   Compiling vec_map v0.8.1
   Compiling csv v1.0.0
   Compiling docopt v1.0.0
   Compiling clap v2.32.0
   Compiling bio v0.21.0
   Compiling rust-htslib v0.20.0
error: failed to compile `breakfast v0.1.0 (file:///home/tools/breakfast)`, intermediate artifacts can be found at `/home/tools/breakfast/target`

Caused by:
  failed to run custom build command for `rust-htslib v0.20.0`
process didn't exit successfully: `/home/tools/breakfast/target/release/build/rust-htslib-a0582a31575f9177/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
